numero = str(input('Digite um número'))
print('A unidade de milhar é: {}'.format(numero[0]))
print('A centena é: {}'.format(numero[1]))
print('A dezena é: {}'.format(numero[2]))
print('A unidade é: {}'.format(numero[3]))